# Generated by Django 3.2.25 on 2025-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='Unique identifier for the template', max_length=255, unique=True, verbose_name='Template ID')),
                ('name', models.CharField(help_text='Name of the template', max_length=255, verbose_name='Template Name')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template', verbose_name='Is Default')),
                ('domain', models.CharField(help_text='Domain associated with this template', max_length=255, verbose_name='Domain')),
                ('source_language', models.CharField(help_text='Source language code', max_length=10, verbose_name='Source Language')),
                ('target_language', models.CharField(help_text='Target language code', max_length=10, verbose_name='Target Language')),
                ('translation_memory_id', models.CharField(blank=True, help_text='ID of the associated translation memory', max_length=255, verbose_name='Translation Memory ID')),
                ('translation_memory_name', models.CharField(blank=True, help_text='Name of the associated translation memory', max_length=255, verbose_name='Translation Memory Name')),
                ('glossary_id', models.CharField(blank=True, help_text='ID of the associated glossary', max_length=255, verbose_name='Glossary ID')),
                ('glossary_name', models.CharField(blank=True, help_text='Name of the associated glossary', max_length=255, verbose_name='Glossary Name')),
                ('description', models.TextField(blank=True, help_text='Description of the template', verbose_name='Description')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time this template was updated', verbose_name='Generated At')),
            ],
            options={
                'verbose_name': 'Translation Template',
                'verbose_name_plural': 'Translation Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='translationtemplate',
            index=models.Index(fields=['template_id'], name='templates_t_templat_ecfc33_idx'),
        ),
        migrations.AddIndex(
            model_name='translationtemplate',
            index=models.Index(fields=['domain', 'source_language', 'target_language'], name='templates_t_domain_8f7483_idx'),
        ),
    ]
