# Generated by Django 3.2.25 on 2025-11-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary_id', models.CharField(help_text='Unique identifier for the glossary (e.g., gls_xxx)', max_length=255, unique=True, verbose_name='Glossary ID')),
                ('name', models.CharField(help_text='Name of the glossary', max_length=255, verbose_name='Glossary Name')),
                ('source_language', models.CharField(help_text='Source language code (e.g., EN, FR)', max_length=10, verbose_name='Source Language')),
                ('target_languages', models.TextField(help_text='Comma-separated list of target language codes', verbose_name='Target Languages')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time this glossary was updated', verbose_name='Generated At')),
                ('domain', models.ForeignKey(blank=True, help_text='Associated domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossaries', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Glossary',
                'verbose_name_plural': 'Glossaries',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['glossary_id'], name='glossaries__glossar_e4ebb0_idx'),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['source_language', 'domain'], name='glossaries__source__76b331_idx'),
        ),
    ]
