# Generated by Django 3.2.25 on 2025-11-29 21:12

from django.db import migrations, models
import django.db.models.deletion


def convert_empty_to_null(apps, schema_editor):
    """Convert empty strings to NULL before changing to ForeignKey"""
    Glossary = apps.get_model('glossaries', 'Glossary')
    Glossary.objects.filter(source_language='').update(source_language=None)


def reverse_convert(apps, schema_editor):
    """Reverse: convert NULL back to empty strings"""
    Glossary = apps.get_model('glossaries', 'Glossary')
    Glossary.objects.filter(source_language__isnull=True).update(source_language='')


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('glossaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='glossary',
            name='glossaries__source__76b331_idx',
        ),
        # First, make the CharField nullable
        migrations.AlterField(
            model_name='glossary',
            name='source_language',
            field=models.CharField(max_length=10, blank=True, null=True, help_text='Source language code'),
        ),
        # Then convert empty strings to NULL
        migrations.RunPython(convert_empty_to_null, reverse_convert),
        # Finally, change to ForeignKey
        migrations.AlterField(
            model_name='glossary',
            name='source_language',
            field=models.ForeignKey(blank=True, help_text='Source language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='glossaries_as_source', to='languages.language'),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['source_language', 'domain'], name='glossaries__source__f9fd1a_idx'),
        ),
    ]
