# Generated by Django 3.2.25 on 2025-12-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0003_domain_to_charfield'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='glossary',
            name='glossaries__source__f9fd1a_idx',
        ),
        migrations.AddField(
            model_name='glossary',
            name='uuid',
            field=models.CharField(db_index=True, default='*', help_text="'*' for system glossaries (available to all), or user UUID for personal glossaries", max_length=255, verbose_name='UUID'),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['source_language', 'domain'], name='glossaries__source__80209f_idx'),
        ),
    ]
