# Generated by Django 3.2.25 on 2025-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossaries', '0004_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='user_glossary_name',
            field=models.CharField(blank=True, help_text='Original name given by the user for personal glossaries', max_length=255, null=True, verbose_name='User Glossary Name'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='name',
            field=models.CharField(help_text='Normalized name of the glossary (e.g., Legal_Accounting_FR or <uuid>_*_FR_EN)', max_length=255, verbose_name='Glossary Name'),
        ),
    ]
