# Generated by Django 3.2.25 on 2025-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(help_text='Unique identifier for the resource', max_length=255, unique=True, verbose_name='Resource ID')),
                ('name', models.CharField(help_text='Name of the resource', max_length=255, verbose_name='Resource Name')),
                ('type', models.CharField(choices=[('memory', 'Translation Memory'), ('glossary', 'Glossary')], help_text='Type of resource (memory or glossary)', max_length=20, verbose_name='Type')),
                ('source_language', models.CharField(blank=True, help_text='Source language code', max_length=10, verbose_name='Source Language')),
                ('target_languages', models.TextField(blank=True, help_text='Comma-separated list of target language codes', verbose_name='Target Languages')),
                ('domains', models.TextField(blank=True, help_text='Comma-separated list of domains', verbose_name='Domains')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time this resource was updated', verbose_name='Generated At')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_id'], name='resources_r_resourc_4a6903_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='resources_r_type_ae8095_idx'),
        ),
    ]
