# Generated by Django 3.2.25 on 2025-11-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('abbreviation', models.CharField(help_text='Language code (ISO 639-1 or custom)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Abbreviation')),
                ('french_name', models.CharField(help_text='Name of the language in French', max_length=100, verbose_name='French Name')),
                ('english_name', models.CharField(help_text='Name of the language in English', max_length=100, verbose_name='English Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['english_name'],
            },
        ),
    ]
