# Generated by Django 3.2.25 on 2025-11-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code for flag display', max_length=2, verbose_name='Country Code'),
        ),
    ]
