# Generated by Django 3.2.25 on 2025-11-29 21:28

from django.db import migrations


def populate_country_codes(apps, schema_editor):
    """Populate country_code field with ISO 3166-1 alpha-2 country codes for flag display"""
    Language = apps.get_model('languages', 'Language')

    # Mapping language code → country code (lowercase for flag-icons library)
    LANGUAGE_TO_COUNTRY = {
        'AR': 'sa',  # Arabic → Saudi Arabia
        'BG': 'bg',  # Bulgarian → Bulgaria
        'CS': 'cz',  # Czech → Czech Republic
        'DA': 'dk',  # Danish → Denmark
        'DE': 'de',  # German → Germany
        'EL': 'gr',  # Greek → Greece
        'EN': 'gb',  # English → United Kingdom
        'ES': 'es',  # Spanish → Spain
        'ET': 'ee',  # Estonian → Estonia
        'FI': 'fi',  # Finnish → Finland
        'FR': 'fr',  # French → France
        'HR': 'hr',  # Croatian → Croatia
        'HU': 'hu',  # Hungarian → Hungary
        'IT': 'it',  # Italian → Italy
        'JA': 'jp',  # Japanese → Japan
        'KO': 'kr',  # Korean → South Korea
        'LT': 'lt',  # Lithuanian → Lithuania
        'LV': 'lv',  # Latvian → Latvia
        'MT': 'mt',  # Maltese → Malta
        'NL': 'nl',  # Dutch → Netherlands
        'NO': 'no',  # Norwegian → Norway
        'PL': 'pl',  # Polish → Poland
        'PT': 'pt',  # Portuguese → Portugal
        'RO': 'ro',  # Romanian → Romania
        'RU': 'ru',  # Russian → Russia
        'SK': 'sk',  # Slovak → Slovakia
        'SL': 'si',  # Slovenian → Slovenia
        'SV': 'se',  # Swedish → Sweden
        'TR': 'tr',  # Turkish → Turkey
        'UK': 'ua',  # Ukrainian → Ukraine
        'ZH': 'cn',  # Chinese → China
        'CA': 'es',  # Catalan → Spain (Catalonia)
        'GA': 'ie',  # Irish → Ireland
        'IS': 'is',  # Icelandic → Iceland
        'zh-Hans': 'cn',  # Chinese Simplified → China
        'zh-TW': 'cn',  # Chinese Traditional → China
        'en-US': 'us',  # English (US) → United States
        'nb': 'no',  # Norwegian Bokmål → Norway
        'pt-br': 'br',  # Portuguese (Brazil) → Brazil
    }

    for lang_code, country_code in LANGUAGE_TO_COUNTRY.items():
        Language.objects.filter(abbreviation=lang_code).update(country_code=country_code)


def reverse_populate(apps, schema_editor):
    """Reverse: clear country codes"""
    Language = apps.get_model('languages', 'Language')
    Language.objects.all().update(country_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_country_code'),
    ]

    operations = [
        migrations.RunPython(populate_country_codes, reverse_populate),
    ]
