# Generated by Django 3.2.25 on 2025-11-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_id', models.CharField(help_text='Unique identifier for the memory (e.g., mem_xxx)', max_length=255, unique=True, verbose_name='Memory ID')),
                ('name', models.CharField(help_text='Name of the translation memory', max_length=255, verbose_name='Memory Name')),
                ('source_language', models.CharField(help_text='Source language code (e.g., EN, FR)', max_length=10, verbose_name='Source Language')),
                ('target_languages', models.TextField(help_text='Comma-separated list of target language codes', verbose_name='Target Languages')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time this memory was updated', verbose_name='Generated At')),
                ('domain', models.ForeignKey(blank=True, help_text='Associated domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Translation Memory',
                'verbose_name_plural': 'Translation Memories',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['memory_id'], name='memories_me_memory__6f8fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['source_language', 'domain'], name='memories_me_source__2daab6_idx'),
        ),
    ]
