# Generated by Django 3.2.25 on 2025-11-29 21:21

from django.db import migrations, models
import django.db.models.deletion


def copy_target_languages(apps, schema_editor):
    """Copy target_languages TextField to target_language ForeignKey"""
    Memory = apps.get_model('memories', 'Memory')
    for memory in Memory.objects.all():
        if memory.target_languages and memory.target_languages.strip():
            # Take the first (and only) language from the comma-separated list
            lang_code = memory.target_languages.strip()
            memory.target_language_id = lang_code
            memory.save(update_fields=['target_language'])


def reverse_copy(apps, schema_editor):
    """Reverse: copy target_language ForeignKey back to target_languages TextField"""
    Memory = apps.get_model('memories', 'Memory')
    for memory in Memory.objects.all():
        if memory.target_language_id:
            memory.target_languages = memory.target_language_id
            memory.save(update_fields=['target_languages'])


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('memories', '0002_auto_20251129_2112'),
    ]

    operations = [
        # First, add the new ForeignKey field
        migrations.AddField(
            model_name='memory',
            name='target_language',
            field=models.ForeignKey(blank=True, help_text='Target language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memories_as_target', to='languages.language'),
        ),
        # Then copy data from target_languages to target_language
        migrations.RunPython(copy_target_languages, reverse_copy),
        # Finally, remove the old TextField
        migrations.RemoveField(
            model_name='memory',
            name='target_languages',
        ),
    ]
