# Generated by Django 3.2.25 on 2025-11-25 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('source_language', models.CharField(blank=True, max_length=10, verbose_name='Source Language')),
                ('target_language', models.CharField(max_length=10, verbose_name='Target Language')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('translated', 'Translated'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('lara_id', models.CharField(blank=True, help_text='ID returned by Lara API', max_length=255, verbose_name='Lara ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('original_file', models.FileField(upload_to='uploads/originals/', verbose_name='Original File')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='uploads/translated/', verbose_name='Translated File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Translation',
                'verbose_name_plural': 'Document Translations',
                'ordering': ['-created_at'],
            },
        ),
    ]
