# Generated by Django 3.2.25 on 2025-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain used for translation', max_length=100, null=True, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='glossary_id',
            field=models.CharField(blank=True, help_text='ID of the glossary used', max_length=255, null=True, verbose_name='Glossary ID'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='template_id',
            field=models.CharField(blank=True, help_text='ID of the template found via find request', max_length=255, null=True, verbose_name='Template ID'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='translation_memory_id',
            field=models.CharField(blank=True, help_text='ID of the translation memory used', max_length=255, null=True, verbose_name='Translation Memory ID'),
        ),
    ]
