# Generated by Django 3.2.25 on 2025-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20251201_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='user_token',
            field=models.CharField(blank=True, db_index=True, help_text='User UUID from Lexa for filtering', max_length=255, null=True, verbose_name='User Token'),
        ),
    ]
