# Generated by Django 3.2.25 on 2025-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_add_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='reviewed_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/reviewed/', verbose_name='Reviewed File'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='template_name',
            field=models.CharField(blank=True, help_text='Template name used for translation', max_length=255, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='tmx_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tmx/', verbose_name='TMX File'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='xliff_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/xliff/', verbose_name='XLIFF File'),
        ),
    ]
