# Generated by Django 3.2.25 on 2025-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_rename_user_token_to_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='payload',
            field=models.TextField(blank=True, help_text='JSON payload sent to LARA API for translation', null=True, verbose_name='Request Payload'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='response',
            field=models.TextField(blank=True, help_text='Response data received from LARA API', null=True, verbose_name='Response Data'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='translation_sec',
            field=models.FloatField(blank=True, help_text='Time taken for translation in seconds', null=True, verbose_name='Translation Time (seconds)'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='translation_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when translation processing started', null=True, verbose_name='Translation Started At'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='User UUID from Lexa', max_length=255, null=True, verbose_name='User UUID'),
        ),
    ]
