# Generated by Django 3.2.25 on 2025-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_add_payload_response_translation_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='lara_sdk_request',
            field=models.TextField(blank=True, help_text='Parameters sent to LARA SDK (filename, source, target, adapt_to, glossaries)', null=True, verbose_name='LARA SDK Request'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='payload',
            field=models.TextField(blank=True, help_text='Parameters received from Lexa (domainId, templateId, glossaries, etc.)', null=True, verbose_name='Lexa Request'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='response',
            field=models.TextField(blank=True, help_text='Translation result metadata (status, duration, file size) or SDK error details', null=True, verbose_name='Translation Result'),
        ),
    ]
