# Generated by Django 3.2.25 on 2025-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20251205_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='characters_count',
            field=models.IntegerField(blank=True, help_text='Number of characters in the source document', null=True, verbose_name='Character Count'),
        ),
        migrations.AddField(
            model_name='documenttranslation',
            name='words_count',
            field=models.IntegerField(blank=True, help_text='Number of words in the source document', null=True, verbose_name='Word Count'),
        ),
    ]
